social-network-engine/config/routes.rb
Sne::Application.routes.draw do
  resources :status
  resources :posts, :only => [:index, :new, :create]
	resources :organizations, :only =>[:show]
	get 'context' => 'posts#post_context'
  get 'checkin' => 'posts#checkin'
  get 'signup' => 'facebook_tab_app#signup'
  get 'signupnofb' => 'Devise::RegistrationsController#create'
  get 'location' => 'posts#where_am_i'

  # All facebook_tab_app actions just get forwarded
  match ':controller/:action', :controller => /facebook_tab_app/

  match '/search' => 'search#search'

  match '/refresh' => 'posts#refresh'
	
	match '/followUser/:id' => 'users#add_friend'
	
	match '/removeUser/:id' => 'users#remove_friend'
		
	match '/followOrganization/:id' => 'organizations#add_organization'
	
	match '/removeOrganization/:id' => 'organizations#remove_organization'
	
	match'/users/posts/:id' => 'users#posts', :as => :users_posts
	match'/users/followings/:id' => 'users#followings', :as => :users_followings
	match'/users/followers/:id' => 'users#followers', :as => :users_followers
	match'/users/organizations/:id' => 'users#organizations', :as => :users_organizations
	match'/users/voip_start/:id' => 'users#voip_start', :as => :user_voip_start
	match'/users/voip_register/:id' => 'users#voip_register', :as => :user_voip_register
	
	match'/organizations/posts/:id' => 'organizations#posts', :as => :organizations_posts
	match'/organizations/followers/:id' => 'organizations#followers', :as => :organizations_followers
	
	match'/reloadPosts' => 'posts#reloadPosts'
	
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  match 'main' => 'posts#index'
  root :to => 'posts#index'
	resources :users, :only=>[:show]
end

social-network-engine/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :address, :latitude, :longitude, :status, :city, :zipcode, :severity
  belongs_to :user
  belongs_to :organization
	#has_one :status, :dependent => :destroy

  validates :text, :length => {
      :minimum   => 1,
      :maximum   => 140,
      :tokenizer => lambda { |str| str.scan(/\w+/) }
  }
  geocoded_by :address
  after_validation :geocode
  reverse_geocoded_by :latitude, :longitude do |obj,results|
    geo = results.first
    unless geo.nil?
      obj.city = geo.city
      obj.zipcode = geo.postal_code
    end
  end
  after_validation :reverse_geocode

  ALL_CLEAR_STATUS = "STATUS_OK"
  NEEDS_ASSISTANCE_STATUS = "STATUS_NEEDS_ASSISTANCE"
  NEEDS_HELP_STATUS = "STATUS_NEEDS_HELP"
  ALL_STATUSES = [ALL_CLEAR_STATUS, NEEDS_ASSISTANCE_STATUS, NEEDS_HELP_STATUS] 
  
  POST_AS_SELF = "SELF"

  validates_inclusion_of :text, :in => ALL_STATUSES, :if => :status?

  def status?
    status == true
  end

  # Filters all posts to those this user is interested in. Also limits the posts
  # returned and allows the specification of an offset.
  # Pass last_id a hash to load newer or older posts, such as {:id=>1, :backward=>false}.
  # :backward => true will load older posts and :backward => false will load newer posts.
  # When last_id is an Id value, new posts will be retrieved.
  # If filter is false, all posts are fetched. Otherwise, we get the posts for
  # the user's friends, organizations, and all cities.
  def self.Filter(user, limit, last_id, location=nil, radius=nil, filter=false) 
    if filter
      # Get the IDs of all organizations the user is following
      org_ids = user.organizations.map{|o| o.id}

      # Add the IDs of the cities since all cities are organizations
      org_ids += Organization::AllCities().map{|c| c.id}

      # Get the IDs of all friends
      friend_ids = user.friends.map{|f| f.id}

      # Include the user's own posts
      friend_ids << user.id

      filter_conditions = ["(user_id IN (?) OR organization_id IN (?))", friend_ids, org_ids]
    else
      # Just get all posts.
      filter_conditions = ""
    end

    # Get posts after the last ID if one was specified
    if last_id.nil? || last_id.length == 0
      conditions = filter_conditions

    else
      if last_id.kind_of?(Hash)
        if last_id[:backward]
          conditions = ["id < ?", last_id[:id]]
        else
          conditions = ["id > ?", last_id[:id]]
        end
      else # last_id is a single Id value
        conditions = ["id > ?", last_id]
      end

      # Add the filters if they exist.
      if not filter_conditions.empty?
        conditions[0] = conditions[0] + " AND " + filter_conditions[0]
        conditions.push(filter_conditions[1])
        conditions.push(filter_conditions[2])
      end
    end

    # Include the user information
    unless  location.is_a? Array
      location = "'#{location}'"
    end

    geoCondition = (!location.nil? && !radius.nil?) ? ".near(#{location}, #{radius.to_i}, :order=>'distance')" : ''
    eval("Post.includes([:user, :organization])#{geoCondition}.find(:all,
        :conditions => conditions,
        :limit => limit,
        :order => 'updated_at DESC')")
  end


  def self.max_distance_from_position(user, location)
    return 0 if location.nil?
    posts = Post.Filter(user, 100, nil)
    max_distance = 0
    posts.each do |post|
      distance = Geocoder::Calculations.distance_between(location, [post.latitude, post.longitude])
      max_distance = distance if distance > max_distance
    end
    max_distance
  end

  def self.get(user, filter=false) 
    if filter
      friend_ids = user.friends.map{|f| f.id}
      friend_ids << user.id
      filter_conditions = ["user_id IN (?)", friend_ids]
    else
      filter_conditions = ""
    end

    eval("Post.find(:all,
        :conditions => filter_conditions,
        :order => 'updated_at DESC')")
  end
end

social-network-engine/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    # Filter all posts for the current user that happened after the specified token
    @f = params[:f]
    @max_distance = 0
    @posts = Post::get(current_user, (not params[:f].nil? and params[:f] == PostsHelper::FilterType::FOLLOWING))

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def refresh
    # when load older pages should specify this
    if (params['backward'] == 'true')
      filter(true)
    else
      filter()
    end

    respond_to do |format|
      format.html { render :partial => "partials/refresh" }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    setupForNewPost

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/checkin
  def checkin
    @status = Status.new

    respond_to do |format|
      format.html
      format.json { render json: @status }
    end
  end

  # GET /post_contect?id=
  def post_context
    session[:post_as] = params[:id]

    respond_to do |format|
      format.json { render :json => {:status => 200} }
    end
  end
  
  # POST /posts
  # POST /posts.json
  def create
    if session[:post_as] != 'SELF'
			organization = Organization.find(session[:post_as])
			organization.posts.create!(params[:post])
		else
		  current_user.posts.create!(params[:post])
		end
		
    respond_to do |format|
      flash[:notice] = "Post created successfully!"
      format.html { redirect_to '/posts#index', notice: 'Post was successfully created.' }
      format.json { render json: @post, status: :created, location: @post }
    end
  end

  def where_am_i
    result = Geocoder.search([params['latitude'].to_f, params['longitude'].to_f])

    address = result.first.address if !result.nil? && result.count > 0
    respond_to do |format|
      format.json {render :json => {:address => result.first.address}}
    end
  end

  def create_status

  end

  def update_status

  end

  def setupForNewPost
    @post = Post.new

    # Get the post as variable from the sesssion.  If it doesn't exist,
    # set it to Post::POST_AS_SELF
    if session[:post_as].nil?
      session[:post_as] = Post::POST_AS_SELF
    end

    @post_as = session[:post_as]

  end

  def filter(older = false)
    # Unless following was specified, don't do filtering
    if not params[:f].nil? and params[:f] == PostsHelper::FilterType::FOLLOWING
      print "\n\nFilter ON\n\n"
      filter = true
    else
      filter = false
    end

    # if (!params['latitude'].nil? && !params['longitude'].nil?)
    #   location = [params['latitude'].to_f, params['longitude'].to_f]
    # elsif (!params['location'].nil?)
    #   location = params['location']
    # end
    token = params['token']
    token = {:id => token, :backward => true} if older
    @max_distance = Post.max_distance_from_position(current_user, location)
    @posts = Post::Filter(current_user, 5, token, nil, nil, filter)
    @token = @posts.first.id if !@posts.nil? && !@posts.first.nil?
    @last_token = @posts.last.id if !@posts.nil? && !@posts.last.nil?
    @path = "../"
  end
	
	def reloadPosts
		filter()
	end
end

social-network-engine/app/helpers/posts_helper.rb
module PostsHelper
  module FilterType
    ALL = "all"
    FOLLOWING = "following"
  end

  # Outputs selected if the item is selected, else not selected
  def self.IsSelected(type, selected)
    if selected == type or (selected.nil? and type == FilterType::ALL)
      "selected=\"selected\""
    else
      ""
    end
  end
end

social-network-engine/app/views/posts/_post_as.html.erb
<% 
	navbar = prefix + "_navbar"
	changeBtn = prefix + "_change"
	picklist = prefix + "_picklist"
	name_label = prefix + "_label"
	radio = prefix + "_radio"
	
	self_value = Post::POST_AS_SELF
	self_id = prefix + "_" + Post::POST_AS_SELF	
	self_label = prefix + "_" + Post::POST_AS_SELF + "_label"
%>

<% if current_user.organizations_managed.length != 0 %>
	<div id="<%= navbar %>" class="ui-bar status-bar" data-selected="<%= post_as %>" data-self="<%= self_value %>">
		<p id="<%= name_label %>"></p>
		<%= link_to "Change", "", :id => changeBtn, :class => "ui-btn-right ui-icon-alt", :data => { :role => "button", :mini => "true", :icon => "arrow-d", :iconpos => "right" } %>
		<fieldset data-role="controlgroup" id="<%= picklist %>" style="display: none">
			<% if post_as == self_value %>
				<input type="radio" name="<%= radio %>" id="<%= self_id %>" value="<%= self_value %>" checked="true">
			<% else %>
			  <input type="radio" name="<%= radio %>" id="<%= self_id %>" value="<%= self_value %>">
			<% end %>
			<label for="<%= self_id %>" id="<%= self_label %>" data-text="<%= current_user.name %>"><%= current_user.name %></label>
			
			<% current_user.organizations_managed.each do |org| %>
				<% 
					org_id = prefix + "_" + org.id.to_s 
					org_label = prefix + "_" + org.id.to_s + "_label"				
				%>
				<% if post_as == org.id %>
					<input type="radio" name="<%= radio %>" id="<%= org_id %>" value="<%= org.id %>" checked="true">
				<% else %>
					<input type="radio" name="<%= radio %>" id="<%= org_id %>" value="<%= org.id %>">
				<% end %>
				<label for="<%= org_id %>" id="<%= org_label %>" data-text="<%= org.name %>"><%= org.name %></label>
			<% end %>
		</fieldset>
	</div>
<% end %>

social-network-engine/app/views/posts/checkin.html.erb
<% content_for :page do %>
		<div data-role="page" data-theme="a" id="postCheckin">
<% end %>

<% content_for :header do %>
	<%= link_to "", posts_path, :class => "header-icon-close", :data => { :role => "button", :transition => "slidedown" } %>	
  <h3>Status</h3>
<% end %>

<% content_for :content do %>
	<div class="post-form">
		<%= form_for @status, :url => {:controller => "status",:action => "create"}, :html => {:method => :post} do |f| %>
			<%= f.hidden_field :latitude %>
			<%= f.hidden_field :longitude %>
			<%= f.hidden_field :status %>
	  <% end %>
	  <%= link_to "I'm OK", "#", :id => "submit_AllClear", :data => {:role => "button", :icon => "good", :iconpos => "top", :theme => "b" } %>
		<%= link_to "Emergency", "#", :id => "submit_NeedHelp", :data => {:role => "button", :icon => "emergency", :iconpos => "top", :theme => "c" } %>
		<%= link_to "Need Assistance", "#", :id => "submit_NeedAssistance", :data => {:role => "button", :icon => "assistance-needed", :iconpos => "top", :theme => "d" } %>
	</div>
  <%= javascript_include_tag "post/common", "post/checkin" %>
<% end %>

social-network-engine/app/views/posts/index.html.erb
<% content_for :page do %>
		<div data-role="page" data-theme="a" id="index">
<% end %>

<% content_for :header do %>
  <div>
    <!-- Header Left Button -->
    <% if user_signed_in? %>
      <%= link_to "", destroy_user_session_path, :class => "header-icon-logout ui-btn-right", :method => "delete", :target => "_self", :data => { :role => "button", :inline => true }, :style => "top:8px" %>
    <% end %>

    <!-- Selection middle -->
    <div style="display:inline-block;top:8px"> 
      <select id="select-filter" onchange="filterBy(this.options[this.selectedIndex].value)">
        <option value="<%= PostsHelper::FilterType::ALL %>" <%= PostsHelper::IsSelected(PostsHelper::FilterType::ALL, @f) %>>All Posts</option>
        <option value="<%= PostsHelper::FilterType::FOLLOWING %>" <%=  PostsHelper::IsSelected(PostsHelper::FilterType::FOLLOWING, @f) %>>Following</option>
      </select>
    </div>

    <!-- Header Right Button -->
    <%= link_to "", search_path, :class => "header-icon-search", :style => "top:-1px", :data => { :role => "button", :transition => "slide", :inline => true } %>

    <% if @max_distance > 1 %>
        <% display = 'block' %>
    <% else %>
        <% display = 'none' %>
    <% end %>
  </div>
  <%= render "partials/geo_filter", :display => display, :max_distance => @max_distance %>
<% end %>

<% content_for :content do %>
	<div class="posts" data-token="<%= @token %>" data-theme="a">
		<% if !@posts.nil? && @posts.length > 0 %>
			<% @posts.each do |post| %>
				<%= render "partials/feed_item", :post => post, :path => @path %>
			<% end %>
		<% end %>
	</div>
<% end %>

<% content_for :scripts do %>
  <%= javascript_include_tag "post/common", "post/index" %>
  <script language="javascript">
    // Formats the URL and redirects.
    function filterBy(filterFieldNum) {
      window.location = window.location.protocol + "//" + window.location.host + "/?f=" + filterFieldNum;
    }
  </script>
<% end %>

social-network-engine/app/views/posts/new.html.erb
<% content_for :page do %>
		<div data-role="page" data-theme="a" id="postNew">
<% end %>

<% content_for :header do %>
	<%= link_to "", posts_path, :class => "header-icon-close", :data => { :role => "button", :transition => "slidedown" } %>	
  <h3>Add New Post</h3>	
	<%= render "post_as", :prefix => "newPost", :post_as => @post_as %>
<% end %>

<% content_for :content do %>
	<div class="post-form">
		<%= form_for @post, :url => {:action => "create"}, :html => { :method => :post, :data => { :ajax => "false" }} do |f| %>
			<%= f.hidden_field :latitude %>
			<%= f.hidden_field :longitude %>
			<%= f.hidden_field :text %>
			<%= f.hidden_field :status, :value => "false" %>
			<%= text_area_tag "new_post_text", "", :placeholder => "What's happening?" %>

      <%= f.radio_button :severity, 0 , style: 'margin-left: -20px; margin-top: 4px'%>
      <%= label :severity, 'OK', style: 'color:grey; margin-left: 20px;' %>
      <%= f.radio_button :severity, 1 , style: 'margin-left: -20px; margin-top: 4px'%>
      <%= label :severity, 'Need assistance', style: 'color:grey; margin-left: 20px;' %>
      <%= f.radio_button :severity, 2 , style: 'margin-left: -20px; margin-top: 4px'%>
      <%= label :severity, 'Emergency', style: 'color:grey; margin-left: 20px;' %>
	  <% end %>
	  <%= link_to "Post", "#", :id => "submit_NewPost", :data => {:role => "button", :theme => "b"} %></li>
	</div>
  <%= javascript_include_tag "post/common","post/new" %>
<% end %>

social-network-engine/app/views/posts/reloadPosts.js.erb
<% if !@posts.nil? && @posts.length > 0 %>
$("#posts").data('last-token', "<%= @last_token %>");
$("[name='postsName']").last().html("<% @posts.each do |post| %><%= escape_javascript(render "partials/feed_item", :post => post, :path => @path) %><% end %>");
<% end %>