social-network-engine/config/routes.rb
Sne::Application.routes.draw do
  resources :status
  resources :posts, :only => [:index, :new, :create]
	resources :organizations, :only =>[:show]
	get 'context' => 'posts#post_context'
  get 'checkin' => 'posts#checkin'
  get 'signup' => 'facebook_tab_app#signup'
  get 'signupnofb' => 'Devise::RegistrationsController#create'
  get 'location' => 'posts#where_am_i'

  # All facebook_tab_app actions just get forwarded
  match ':controller/:action', :controller => /facebook_tab_app/

  match '/search' => 'search#search'

  match '/refresh' => 'posts#refresh'
	
	match '/followUser/:id' => 'users#add_friend'
	
	match '/removeUser/:id' => 'users#remove_friend'
		
	match '/followOrganization/:id' => 'organizations#add_organization'
	
	match '/removeOrganization/:id' => 'organizations#remove_organization'
	
	match'/users/posts/:id' => 'users#posts', :as => :users_posts
	match'/users/followings/:id' => 'users#followings', :as => :users_followings
	match'/users/followers/:id' => 'users#followers', :as => :users_followers
	match'/users/organizations/:id' => 'users#organizations', :as => :users_organizations
	match'/users/voip_start/:id' => 'users#voip_start', :as => :user_voip_start
	match'/users/voip_register/:id' => 'users#voip_register', :as => :user_voip_register
	
	match'/organizations/posts/:id' => 'organizations#posts', :as => :organizations_posts
	match'/organizations/followers/:id' => 'organizations#followers', :as => :organizations_followers
	
	match'/reloadPosts' => 'posts#reloadPosts'
	
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  match 'main' => 'posts#index'
  root :to => 'posts#index'
	resources :users, :only=>[:show]
end

social-network-engine/app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :facebook_id, :name, :is_city, :profile_pic

  # The users who are interested in this organization
  has_and_belongs_to_many :users

  # The users who can manage this organization
  has_and_belongs_to_many :managers, :class_name => "User", :foreign_key => "organization_id", :association_foreign_key => "user_id", :join_table => "organization_administrators"

  # Any posts made by the organization
  has_many :posts

  # Return all cities
  def self.AllCities
    Organization.find(:all, :conditions => ["is_city = ?", true])
  end
end

social-network-engine/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authenticate_user!
  def show	
		@organization = Organization.find(params[:id])
		@posts = @organization.posts.reverse
		@path = "../"
    respond_to do |format|
      format.html # show.html.erb
    end
  end
	
	# POST /followOrganization/?id=
  def add_organization
		organization = Organization.find(params[:id])
		if !current_user.organizations.include?(organization)	
			current_user.organizations << Organization.find(params[:id])
		end
		respond_to do |format|
      format.json { head :ok }
    end
  end
	
	# POST /removeOrganization/?id=
  def remove_organization
		organization = Organization.find(params[:id])
		if current_user.organizations.include?(organization)	
			current_user.organizations.delete(organization)
		end
		respond_to do |format|
      format.json { head :ok }
    end
  end	
	
	def followers
		@organization = Organization.find(params[:id])
		@path = "../"
		@feedItemId = "organizationFollowerFeedItemId"		
	end
	
	def posts
		@organization = Organization.find(params[:id])
		@posts = @organization.posts.reverse
		@path = "../"
	end
	
end

social-network-engine/app/views/organizations/followers.js.erb
$(".organizationPostsButton").removeClass("ui-btn-active");
$(".organizationFriendsButton").addClass("ui-btn-active");

<% if !@organization.users.nil? && @organization.users.length > 0 %>
	$(".organizationData").html("<% @organization.users.each do |user| %><%= escape_javascript(render "partials/user_item", :user => user, :path => @path, :feedItemId => @feedItemId) %><% end %>");
<% else %>
	$(".organizationData").html("<%= @organization.name %> has no followers.");
<% end %>

social-network-engine/app/views/organizations/posts.js.erb
$(".organizationPostsButton").addClass("ui-btn-active");
$(".organizationFriendsButton").removeClass("ui-btn-active");

$(".followingsButton").addClass("ui-btn-active");
<% if !@posts.nil? && @posts.length > 0%>
$(".organizationData").html("<% @posts.each do |post| %><%= escape_javascript(render "partials/feed_item", :post => post, :path => @path) %><% end %>");
<% else %>
	$(".organizationData").html("<%= @organization.name %> has no posts.");
<% end %>

social-network-engine/app/views/organizations/show.html.erb
<% content_for :page do %>
		<div data-role="page" data-theme="a" id="organizationsShow">
<% end %>

<% content_for :header do %>
	<%= link_to "", posts_path, :class => "header-icon-close", :data => { :role => "button", :transition => "slidedown" } %>	
  <h3>Organization Profile</h3>	
<% end %>

<% content_for :content do %>
	<div class="feed-item" style="min-width:300px;">
		<div class="feed-header">
			<div class="user-left">
				<img src="<%= @path %><%= @organization.profile_pic %>" class="author-img"/>
				<h2 class="profile-name"><%= @organization.name %></h2>
			</div>
			<div class="user-right-profile">
				<% unless current_user.organizations.include? @organization%>
					<%= link_to_function "Follow", "followOrganization(#{@organization.id}, #{current_user.id})", :class => 'addOrganizationButton', :name => "followOrganization#{@organization.id}"  %>
					<%= link_to_function "Remove", "removeOrganization(#{@organization.id}, #{current_user.id})", :class => 'disabled removeOrganizationButton', :name => "removeOrganization#{@organization.id}"  %>			
				<% else %>
					<%= link_to_function "Follow", "followOrganization(#{@organization.id}, #{current_user.id})", :class => 'disabled addOrganizationButton', :name => "followOrganization#{@organization.id}"  %>
					<%= link_to_function "Remove", "removeOrganization(#{@organization.id}, #{current_user.id})", :class => 'removeOrganizationButton', :name => "removeOrganization#{@organization.id}"  %>			
				<% end %>	
			</div>
				<div class="profile-container" data-role="navbar">
					<ul>
						<li><%= link_to "Posts", organizations_posts_path, :remote => true, :data => {:role => "button", :icon => "posts", :iconpos => "top"}, :class => 'organizationPostsButton ui-btn-active', :id => @organization.id %></li>
						<li><%= link_to "Followers", organizations_followers_path, :remote => true, :data => {:role => "button", :icon => "friends", :iconpos => "top"}, :class => 'organizationFriendsButton', :id => @organization.id %></li>
					</ul>
			</div>			
		</div>
	</div>

	<div class="organizationData" data-token="<%= @token %>" data-theme="a">
		<% if !@posts.nil? && @posts.length > 0 %>
			<% @posts.each do |post| %>
				<%= render "partials/feed_item", :post => post, :path => @path %>
			<% end %>
		<% else %>	
			<%= @organization.name %> has no posts.
		<% end %>	
	</div>
<% end %>