social-network-engine/config/routes.rb
Sne::Application.routes.draw do
  resources :status
  resources :posts, :only => [:index, :new, :create]
	resources :organizations, :only =>[:show]
	get 'context' => 'posts#post_context'
  get 'checkin' => 'posts#checkin'
  get 'signup' => 'facebook_tab_app#signup'
  get 'signupnofb' => 'Devise::RegistrationsController#create'
  get 'location' => 'posts#where_am_i'

  # All facebook_tab_app actions just get forwarded
  match ':controller/:action', :controller => /facebook_tab_app/

  match '/search' => 'search#search'

  match '/refresh' => 'posts#refresh'
	
	match '/followUser/:id' => 'users#add_friend'
	
	match '/removeUser/:id' => 'users#remove_friend'
		
	match '/followOrganization/:id' => 'organizations#add_organization'
	
	match '/removeOrganization/:id' => 'organizations#remove_organization'
	
	match'/users/posts/:id' => 'users#posts', :as => :users_posts
	match'/users/followings/:id' => 'users#followings', :as => :users_followings
	match'/users/followers/:id' => 'users#followers', :as => :users_followers
	match'/users/organizations/:id' => 'users#organizations', :as => :users_organizations
	match'/users/voip_start/:id' => 'users#voip_start', :as => :user_voip_start
	match'/users/voip_register/:id' => 'users#voip_register', :as => :user_voip_register
	
	match'/organizations/posts/:id' => 'organizations#posts', :as => :organizations_posts
	match'/organizations/followers/:id' => 'organizations#followers', :as => :organizations_followers
	
	match'/reloadPosts' => 'posts#reloadPosts'
	
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  match 'main' => 'posts#index'
  root :to => 'posts#index'
	resources :users, :only=>[:show]
end

social-network-engine/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
		 
  validates_presence_of :email

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :profile_pic, :email, :password, :password_confirmation, :remember_me, :token_expiration, :provider, :uid, :token, :voip_ext
  has_many :posts, :dependent => :destroy

  # has_many :status, :dependent => :destroy

  # The user's friends
  has_and_belongs_to_many :friends, :class_name => "User", :foreign_key => "user_id", :association_foreign_key => "friend_id", :join_table => "friends_users"
	has_and_belongs_to_many :followers, :class_name => "User", :foreign_key => "friend_id", :association_foreign_key => "user_id", :join_table => "friends_users"

  # The organizations the user administers
  has_and_belongs_to_many :organizations_managed, :class_name => "Organization", :foreign_key => "user_id", :association_foreign_key => "organization_id", :join_table => "organization_administrators"

  # The organizations the user is interested in
  has_and_belongs_to_many :organizations

  # Allows us to mock util for tests
  @@util_save_picture = Util.method(:save_picture)

  def UpdateFriends(facebook_friend_ids)
    # Look for existing users who are Facebook friends
    existing_friends = User.find(:all, :conditions => ["uid IN (?)", facebook_friend_ids])
    if not existing_friends.nil?
      # Mirror the friends in Facebook
      self.friends.destroy_all
      self.friends << existing_friends
    end
  end

  def UpdateOrganizations(org_ids)
    # Look for existing organizations that exist in SSN
    existing_orgs = Organization.find(:all, :conditions => ["facebook_id IN (?)", org_ids])
    if not existing_orgs.nil?
      # Mirror the organizations in Facebook
      self.organizations.destroy_all
      self.organizations << existing_orgs
    end
  end

  def UpdateProfilePicture(profile_pic)
    profile_pic_name = @@util_save_picture.call(profile_pic)
    self.profile_pic = profile_pic_name
    self.save!
  end

  # Updates a user's friends, organizations, and profile picture. 
  # TODO: Make this smarter about downloading the picture, try not to change it
  # if it has not changed.
  def UpdateData(friend_ids, org_ids, profile_pic)
    self.UpdateFriends(friend_ids)
    self.UpdateOrganizations(org_ids)
    self.UpdateProfilePicture(profile_pic)
  end
end

social-network-engine/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # Allows us to mock util for tests
  @@util_save_picture = Util.method(:save_picture)

  def get_expiration(auth)
    if not auth['credentials']['expires'].nil? and not auth['credentials']['expires']
      expiration_date = Time.now().advance(:years => 100).to_datetime
    else
      expiration_date = Time.at(auth['credentials']['expires_at']).to_datetime
    end

    expiration_date
  end


  def facebook
    auth = request.env["omniauth.auth"]

    @user = User.where(:provider => auth.provider, :uid => auth.uid).first

    if @user.nil?
      # The user came from the signup flow
      if params[:state] == "signup"
        # User is new, continue flow

        # Get user profile picture
        profile_pic_name = @@util_save_picture.call(auth['info']['image'])

        # Create user's account
        @user = User.create(
            name:auth['info']['name'],
            profile_pic:profile_pic_name,
            provider:auth.provider,
            uid:auth.uid,
            email:auth['info']['email'],
            password:Devise.friendly_token[0,20],
            token:auth['credentials']['token'],
            token_expiration:get_expiration(auth))

        sign_in @user
        redirect_to "/facebook_tab_app/load_account"
      else
        redirect_to :root
      end
    else
      # Sign user in and refresh Facebook token
      sign_in @user

      @user.update_attributes!(
          :token => auth['credentials']['token'],
          :token_expiration => get_expiration(auth))

      # Redirect to done if the user is in the signup flow
      if params[:state] == "signup"
        redirect_to "/facebook_tab_app/done"
      else
        redirect_to :root
      end
    end
  end
end

social-network-engine/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user! 
  def show
		@user = User.find(params[:id])
		@posts = @user.posts.reverse

		@path = "../"
    respond_to do |format|
      format.html # show.html.erb
    end
  end
	
  # POST followUser/?id=
  def add_friend
		user = User.find(params[:id])
		if !current_user.friends.include?(user)	
			current_user.friends << User.find(params[:id])
		end
		respond_to do |format|
      format.json { head :ok }
    end
  end
	
	# POST removeUser/?id=
  def remove_friend
		user = User.find(params[:id])
		if current_user.friends.include?(user)	
			current_user.friends.delete(User.find(params[:id]))
		end
		respond_to do |format|
      format.json { head :ok }
    end
  end
	
	def followings
		@user = User.find(params[:id])
		@path = "../"
		@feedItemId = "followingFeedItemId"
	end
	
	def followers
		@user = User.find(params[:id])
		@path = "../"
		@feedItemId = "userFollowerFeedItemId"
	end
	
	def posts
		@user = User.find(params[:id])
		@posts = @user.posts.reverse
		@path = "../"
	end
	
	def organizations
		@user = User.find(params[:id])
		@path = "../"
		if(current_user == @user)
			@feedItemId = "followingFeedItemId"
		end
	end

	def voip_start
		@user = User.find(params[:id])
		voip_user_check(@user)
	end

	# voip_register:
	# Assign VoIP extension from the first number to
	# the last number consecutively (e.g. 401-600)
	def voip_register
		@user = User.find(params[:id])
		if voip_user_check(@user)
			first = 400 # The first extension assigned
			last = 600 # The largest extension assigned
			assigned = User.maximum("voip_ext") # The largest currently assigned extension

			if assigned.nil?
				@user.voip_ext = first
			elsif assigned == last
				# Todo: redirect to error message
			else
				@user.voip_ext = assigned + 1
				@user.save
			end
		end
	end

	# voip_user_check:
	# Check if the user is adding VoIP extension to its own account
	# and s/he does not have extension yet
	def voip_user_check(user)
		if user != current_user || !(user.voip_ext.nil?)
			redirect_to root_path
			return false
		else
			return true
		end
	end
end

social-network-engine/app/views/users/followers.js.erb
$(".userPostsButton").removeClass("ui-btn-active");
$(".userFollowingsButton").removeClass("ui-btn-active");
$(".userFriendsButton").addClass("ui-btn-active");
$(".userOrganizationsButton").removeClass("ui-btn-active");

<% if !@user.followers.nil? && @user.followers.length > 0 %>
	$(".userData").html("<% @user.followers.each do |follower| %><%= escape_javascript(render "partials/user_item", :user => follower, :path => @path, :feedItemId => @feedItemId) %><% end %>");
<% else %>
	$(".userData").html("<%= @user.name %> has no followers.");
<% end %>

social-network-engine/app/views/users/followings.js.erb
$(".userPostsButton").removeClass("ui-btn-active");
$(".userFollowingsButton").addClass("ui-btn-active");
$(".userFriendsButton").removeClass("ui-btn-active");
$(".userOrganizationsButton").removeClass("ui-btn-active");

<% if !@user.friends.nil? && @user.friends.length > 0 %>
$(".userData").html("<% @user.friends.each do |friend| %><%= escape_javascript(render "partials/user_item", :user => friend, :path => @path, :feedItemId => @feedItemId) %><% end %>");
<% else %>
	$(".userData").html("<%= @user.name %> is not following anyone.");
<% end %>

social-network-engine/app/views/users/organizations.js.erb
$(".userPostsButton").removeClass("ui-btn-active");
$(".userFollowingsButton").removeClass("ui-btn-active");
$(".userFriendsButton").removeClass("ui-btn-active");
$(".userOrganizationsButton").addClass("ui-btn-active");

<% if !@user.organizations.nil? && @user.organizations.length > 0 %>
$(".userData").html("<% @user.organizations.each do |organization| %><%= escape_javascript(render "partials/organization_item", :organization => organization, :path => @path, :feedItemId => @feedItemId) %><% end %>");
<% else %>
	$(".userData").html("<%= @user.name %> is not following or associated with any organizations.");
<% end %>

social-network-engine/app/views/users/posts.js.erb
$(".userPostsButton").addClass("ui-btn-active");
$(".userFollowingsButton").removeClass("ui-btn-active");
$(".userFriendsButton").removeClass("ui-btn-active");
$(".userOrganizationsButton").removeClass("ui-btn-active");

<% if !@posts.nil? && @posts.length > 0%>
$(".userData").html("<% @posts.each do |post| %><%= escape_javascript(render "partials/feed_item", :post => post, :path => @path) %><% end %>");
<% else %>
	$(".userData").html("<%= @user.name %> has no posts.");
<% end %>

social-network-engine/app/views/users/show.html.erb
<% content_for :page do %>
		<div data-role="page" data-theme="a" id="usersShow">
<% end %>

<% content_for :header do %>
	<%= link_to "", posts_path, :class => "header-icon-close", :data => { :role => "button", :transition => "slidedown" } %>	
  <h3>Profile</h3>	
<% end %>

<% content_for :content do %>

	<div class="feed-item" style="min-width:300px;">
		<div class="feed-header">
		
			<div class="user-left">
				<img src="<%= @path %><%= @user.profile_pic %>" class="author-img"/>
				<h2 class="profile-name"><%= @user.name %></h2>

        <p class="profile-callno">
          <% if current_user == @user %>
            <% if current_user.voip_ext.nil? %>
              No IP phone registered: <%= link_to "register your IP phone", user_voip_start_path %>
            <% else %>
              Your IP phone number: <%= @user.voip_ext %>
            <% end %>
          <% elsif !(@user.voip_ext.nil?) %>
            <% if current_user.voip_ext.nil? %>
              This user has IP phone: <%= link_to "register your IP phone", user_voip_start_path(current_user) %>
            <% else %>
              IP phone number: <a href="sip://<%= @user.voip_ext %>"><%= @user.voip_ext %></a>
            <% end %>
          <% end %>
        </p>
			</div>
			
			<% unless current_user == @user%>
				<div class="user-right-profile">
					<% unless current_user.friends.include? @user%>
						<%= link_to_function "Follow", "followUser(#{@user.id}, #{current_user.id})", :class => 'addUserButton', :name => "followUser#{@user.id}"  %>
						<%= link_to_function "Remove", "removeUser(#{@user.id}, #{current_user.id})", :class => 'disabled removeUserButton', :name => "removeUser#{@user.id}"  %>
					<% else %>
						<%= link_to_function "Follow", "followUser(#{@user.id}, #{current_user.id})", :class => 'addUserButton disabled', :name => "followUser#{@user.id}"  %>
						<%= link_to_function "Remove", "removeUser(#{@user.id}, #{current_user.id})", :class => 'removeUserButton', :name => "removeUser#{@user.id}" %>
					<% end %>
				</div>
			<% end %>	
					
			<div class="profile-container" data-role="navbar">
				<ul>
					<li><%= link_to "Posts", users_posts_path, :remote => true, :data => {:role => "button", :icon => "posts", :iconpos => "top"}, :class => 'userPostsButton ui-btn-active', :id => @user.id %></li>
					<li><%= link_to "Following", users_followings_path, :remote => true, :data => {:role => "button", :icon => "friends", :iconpos => "top"}, :class => 'userFollowingsButton', :id => @user.id %></li>
					<li><%= link_to "Followers", users_followers_path, :remote => true, :data => {:role => "button", :icon => "friends", :iconpos => "top"}, :class => 'userFriendsButton', :id => @user.id %></li>
					<li><%= link_to "Orgs", users_organizations_path, :remote => true, :data => {:role => "button", :icon => "organizations", :iconpos => "top"}, :class => 'userOrganizationsButton', :id => @user.id %></li>
				</ul>
			</div>	
			
		</div>
	</div>	
	<div class="userData" data-token="<%= @token %>" data-theme="a">
		<% if !@posts.nil? && @posts.length > 0 %>
			<% @posts.each do |post| %>
				<%= render "partials/feed_item", :post => post, :path => @path %>
			<% end %>
		<% else %>	
			<%= @user.name %> has no posts.
		<% end %>	
	</div>
<% end %>

social-network-engine/app/views/users/voip_register.html.erb
<% content_for :page do %>
		<div data-role="page" data-theme="a" id="usersShow">
<% end %>

<% content_for :header do %>
	<%= link_to "", posts_path, :class => "header-icon-close", :data => { :role => "button", :transition => "slidedown" } %>
  <h3>Set up IP phone</h3>
<% end %>

<% content_for :content do %>
  <div class="login">
    <h3>Your IP phone number</h3>
    <p data-theme="a">Congratulations! You got a phone number <%= @user.voip_ext %>! Please set up your account in the IP phone app.</p>
    <h3>Set up IP phone app</h3>
    <p data-theme="a">In your IP phone up, please open account settings and add following information.</p>
  </div>
<% end %>

social-network-engine/app/views/users/voip_start.html.erb
<% content_for :page do %>
		<div data-role="page" data-theme="a" id="usersShow">
<% end %>

<% content_for :header do %>
	<%= link_to "", posts_path, :class => "header-icon-close", :data => { :role => "button", :transition => "slidedown" } %>
  <h3>Register IP phone</h3>
<% end %>

<% content_for :content do %>
  <div class="login">
    <h3>Install IP phone application</h3>
    <p data-theme="a">To make IP calls, you need to install IP phone applicaiton on your smartphone.
      We recommend Zoiper, which are available for both iOS and Android.
      After you install the application, please proceed to obtain your phone number.</p>
    <%= link_to user_voip_register_path, :class => 'facebook-btn', :rel => 'external', :data => { :role => 'button', :theme => 'b' } do %>
			<p>Obtain phone number</p>
		<% end %>
  </div>
<% end %>