social-network-engine/config/routes.rb
Sne::Application.routes.draw do
  resources :status
  resources :posts, :only => [:index, :new, :create]
	resources :organizations, :only =>[:show]
	get 'context' => 'posts#post_context'
  get 'checkin' => 'posts#checkin'
  get 'signup' => 'facebook_tab_app#signup'
  get 'signupnofb' => 'Devise::RegistrationsController#create'
  get 'location' => 'posts#where_am_i'

  # All facebook_tab_app actions just get forwarded
  match ':controller/:action', :controller => /facebook_tab_app/

  match '/search' => 'search#search'

  match '/refresh' => 'posts#refresh'
	
	match '/followUser/:id' => 'users#add_friend'
	
	match '/removeUser/:id' => 'users#remove_friend'
		
	match '/followOrganization/:id' => 'organizations#add_organization'
	
	match '/removeOrganization/:id' => 'organizations#remove_organization'
	
	match'/users/posts/:id' => 'users#posts', :as => :users_posts
	match'/users/followings/:id' => 'users#followings', :as => :users_followings
	match'/users/followers/:id' => 'users#followers', :as => :users_followers
	match'/users/organizations/:id' => 'users#organizations', :as => :users_organizations
	match'/users/voip_start/:id' => 'users#voip_start', :as => :user_voip_start
	match'/users/voip_register/:id' => 'users#voip_register', :as => :user_voip_register
	
	match'/organizations/posts/:id' => 'organizations#posts', :as => :organizations_posts
	match'/organizations/followers/:id' => 'organizations#followers', :as => :organizations_followers
	
	match'/reloadPosts' => 'posts#reloadPosts'
	
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  match 'main' => 'posts#index'
  root :to => 'posts#index'
	resources :users, :only=>[:show]
end

social-network-engine/app/views/partials/_checkin_item.html.erb
<div class="feed-item">
  <a href="<%= user_path(status.user) %>" class="feed-header">
    <img src="<%= path %><%= status.user.profile_pic %>" class="author-img"/>
    <h2 class="author-name"><%= status.user.name %></h2>
    <% if !status.distance.nil? && !status.direction.nil? && !status.clear %>
        <p class="post-time"><%= '%.2f' % status.distance %> miles
          <%= status.direction %></p>
    <% end %>
    <% if status.status %>
        <% if status.status == Post::ALL_CLEAR_STATUS %>
            <div class="status">
              <%= image_tag "glyphicons/glyphicons_193_circle_ok.png" %>
            </div>
            <a style="visibility: hidden" class="all-clear" data-role="button" data-theme="b" data-mini="true" data-inline="true">All Clear</a>
        <% elsif status.status == Post::NEEDS_ASSISTANCE_STATUS %>
            <div class="status">
              <%= image_tag "glyphicons/glyphicons_196_circle_exclamation_mark.png" %>
            </div>
            <% if status.clear %>
                <a data-action="all-clear" class="all-clear" data-role="button" data-theme="b" data-mini="true" data-inline="true">All Clear</a>
            <% else %>
                <a style="visibility: hidden" class="all-clear" data-role="button" data-theme="b" data-mini="true" data-inline="true">All Clear</a>
            <% end %>
        <% elsif status.status == Post::NEEDS_HELP_STATUS %>
            <div class="status">
              <%= image_tag "glyphicons/glyphicons_298_hospital.png" %>
            </div>
            <% if status.clear %>
                <a data-action="all-clear" class="all-clear" data-role="button" data-theme="b" data-mini="true" data-inline="true">All Clear</a>
            <% else %>
                <a style="visibility: hidden" class="all-clear" data-role="button" data-theme="b" data-mini="true" data-inline="true">All Clear</a>
            <% end %>
        <% end %>
    <% end %>
  </a>
    <% if status.status == Post::ALL_CLEAR_STATUS %>
        <div class="feed-content-green">
          <p class="feed-text">Everything is OK</p>
        </div>
    <% elsif status.status == Post::NEEDS_ASSISTANCE_STATUS %>
        <div class="feed-content-yellow">
          <p class="feed-text">Need Help ASAP</p>

        </div>
    <% elsif status.status == Post::NEEDS_HELP_STATUS %>
        <div class="feed-content-red">
          <p class="feed-text">Immediate Help Required</p>
        </div>
    <% end %>
</div>

social-network-engine/app/views/partials/_feed_item.html.erb
<% if post.severity.nil? %>
  <div class="feed-item">
<% else %>
  <% case post.severity %>
    <% when 0 %>
      <div class="feed-item-ok">
    <% when 1 %>
      <div class="feed-item-assistance">
    <% when 2 %>
    <div class="feed-item-emergency">
    <% else %>
  <% end %>
<% end %>

    <% if post.organization.nil? %>
			<a href="<%= user_path(post.user) %>" class="feed-header">
        <img src="<%= path %><%= post.user.profile_pic %>" class="author-img"/>
        <h2 class="author-name"><%= post.user.name %></h2>
    <% else %>
			<a href="<%= organization_path(post.organization) %>" class="feed-header">
        <img src="<%= path %><%= post.organization.profile_pic %>" class="author-img"/>
        <h2 class="author-name"><%= post.organization.name %></h2>
    <% end %>

    <p class="post-time"><%= time_ago_in_words(post.created_at) %> ago
      <% if !post.city.nil? || !post.zipcode.nil? %>
            near <%= post.city %> <%= post.zipcode %>
      <% end %>
      <% if !post.severity.nil? %>
        <% case post.severity %>
          <% when 0 %>
            OK
          <% when 1 %>
            Need Assistance
          <% when 2 %>
            Emergency
          <% else %>
        <% end %>
      <% else %>
        No Status
      <% end %>
    </p>
  </a>
  <div class="feed-content">
    <p class="feed-text"><%= post.text %></p>
  </div>
</div>

social-network-engine/app/views/partials/_geo_filter.html.erb
<div id="geo-filter-panel" class="ui-bar status-bar gray" style="display: none">
  <p id="filter-summary">All posts</p>
  <%= link_to "Filter", "", :id => "filter-btn", :class => "ui-btn-right ui-icon-alt filter", :data => {:role => "button", :mini => "true", :icon => "arrow-d", :iconpos => "right"} %>
  <%= link_to "Clear Filter", "", :id => "clear-filter-btn", :style => "display:none", :class => "ui-btn-right ui-icon-alt filter", :data => {:role => "button", :mini => "true", :icon => "delete", :iconpos => "left"} %>

  <fieldset data-role="controlgroup" id="geo-filter" style="display: none;">
    <!--splitter-->
    <div style="border-top: 1px solid #b3b3b3; height: 10px; margin-left: -20px; margin-right: -20px"></div>
    <div style="display: none">
      <label style="line-height: 32px;">Address:</label>
      <% location_icon = image_tag "glyphicons/glyphicons_233_direction.png", :size => "15x15" %>
      <%= link_to location_icon, "", :id => "current-location-btn", :class => "ui-btn-corner-all", :data => {:role => "button", :mini => "true"} %>

      <div style="clear: both;"></div>
      <input type="text" maxlength="150" data-mini="false" name="location" id="location" value="" placeholder="Zip code or valid address">
    </div>

    <label style="line-height: 32px;">Distance (miles):</label>
    <input type="range" id="radius" name="radius" id="slider-fill-mini" value="<%= max_distance %>" min="0" max="<%= max_distance %>" step="<%= max_distance> 5 ? (max_distance/5).ceil : 1 %>" data-highlight="true">

  </fieldset>

</div>

social-network-engine/app/views/partials/_menu.html.erb
<% content_for :footer do %>
	<div data-role="navbar">
		<ul>
      <li><%= link_to "Timeline", posts_path, :data => { :role => "button", :icon =>"timeline", :iconpos => "top", :transition => "slideup", :id=>"status" } %></li>
      <li><%= link_to "Post", new_post_path, :data => { :role => "button", :icon =>"post", :iconpos => "top", :transition => "slideup" } %></li>
			<li><%= link_to "Profile", current_user, :data => { :role => "button", :icon =>"profile", :iconpos => "top", :transition => "slideup" } %></li>
      <li><%= link_to "Info", '#', :data => { :role => "button", :icon =>"extra-content", :iconpos => "top", :transition => "slideup" } %></li>
			 <!-- <li><%= link_to "Settings", "#settingsDialog", :data => { :role => "button", :icon =>"settings", :iconpos => "top", :transition => "slideup" } %></li> -->
		</ul>
	</div>
<% end %>

social-network-engine/app/views/partials/_organization_item.html.erb
<div class="feed-item" <% if !feedItemId.nil? %> id="<%= feedItemId %><%= organization.id %>"<% end %>>
	<div>
		<div class="user-left">
			<a href="<%= organization_path(organization) %>"class="feed-header">
				<img src="<%= path %><%= organization.profile_pic %>" class="author-img"/>
				<h2 class="author-name"><%= organization.name %></h2>
			</a>
			<div class="feed-content ">
				<p class="feed-text">
					&nbsp;
				</p>
			</div>
		</div>
			<div class="user-right">
			<% unless current_user.organizations.include? organization%>
				<%= link_to_function "Follow", "followOrganization(#{organization.id})", :class => 'addOrganizationButton', :name => "followOrganization#{organization.id}"  %>
				<%= link_to_function "Remove", "removeOrganization(#{organization.id})", :class => 'disabled removeOrganizationButton', :name => "removeOrganization#{organization.id}"  %>			
			<% else %>
				<%= link_to_function "Follow", "followOrganization(#{organization.id})", :class => 'disabled addOrganizationButton', :name => "followOrganization#{organization.id}"  %>
				<%= link_to_function "Remove", "removeOrganization(#{organization.id})", :class => 'removeOrganizationButton', :name => "removeOrganization#{organization.id}"  %>			
			<% end %>	
			</div>
	</div>
</div>

social-network-engine/app/views/partials/_refresh.html.erb
<div>
  <span id="token" style="display: none"><%= @token %></span>
  <span id="last-token" style="display: none"><%= @last_token %></span>
  <span id="max-distance" style="display: none"><%= @max_distance %></span>
  <% if !@posts.nil? && @posts.length > 0 %>
    <%= debug @posts %>
      <% @posts.each do |post| %>
          <%= render "partials/feed_item", :post => post, :path => @path%>
      <% end %>
  <% end %>
</div>

social-network-engine/app/views/partials/_user_item.html.erb
<div class="feed-item" style="min-width:300px;" <% if !feedItemId.nil? %> id="<%= feedItemId %><%= user.id %>"<% end %>>
	<div>
		<div class="user-left">
			<a href="<%= user_path(user) %>" class="feed-header">
				<img src="<%= path %><%= user.profile_pic %>" class="author-img"/>

				<h2 class="author-name"><%= user.name %></h2>
			</a>
			<div class="feed-content">
				<p class="feed-text">
					&nbsp;
				</p>
			</div>
		</div>
		<% unless current_user == user%>
			<div class="user-right">
				<% unless current_user.friends.include? user%>
					<%= link_to_function "Follow", "followUser(#{user.id})", :class => 'addUserButton', :name => "followUser#{user.id}"  %>
					<%= link_to_function "Remove", "removeUser(#{user.id})", :class => 'disabled removeUserButton', :name => "removeUser#{user.id}"  %>
				<% else %>
					<%= link_to_function "Follow", "followUser(#{user.id})", :class => 'addUserButton disabled', :name => "followUser#{user.id}"  %>
					<%= link_to_function "Remove", "removeUser(#{user.id})", :class => 'removeUserButton', :name => "removeUser#{user.id}" %>
				<% end %>
			</div>
		<% end %>			
	</div>
</div>